import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as THREE from 'three';
import { OBJExporter } from 'three/examples/jsm/exporters/OBJExporter.js';
import { buildScene } from '../src/buildScene.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(__dirname, '..', 'output');

function buildMtl(scene) {
  const materials = new Map();
  scene.traverse((child) => {
    if (child.isMesh && child.material && !materials.has(child.material.name)) {
      materials.set(child.material.name, child.material);
    }
  });

  let mtl = '# Generated by 3d-model-tool — approximate materials, not physically calibrated\n\n';
  for (const [name, material] of materials) {
    const { r, g, b } = material.color;
    mtl += `newmtl ${name}\n`;
    mtl += `Ka ${r.toFixed(4)} ${g.toFixed(4)} ${b.toFixed(4)}\n`;
    mtl += `Kd ${r.toFixed(4)} ${g.toFixed(4)} ${b.toFixed(4)}\n`;
    mtl += `Ks ${(material.metalness * 0.5).toFixed(4)} ${(material.metalness * 0.5).toFixed(4)} ${(material.metalness * 0.5).toFixed(4)}\n`;
    mtl += `Ns ${Math.max(1, (1 - material.roughness) * 200).toFixed(2)}\n`;
    mtl += 'd 1.0\nillum 2\n\n';
  }
  return mtl;
}

async function main() {
  const scene = buildScene(THREE);
  scene.updateMatrixWorld(true);

  const exporter = new OBJExporter();
  const objBody = exporter.parse(scene);
  const objContent =
    '# Generated by 3d-model-tool from reference photos — approximate, NOT a measured/surveyed model\n' +
    'mtllib model.mtl\n\n' +
    objBody;

  const mtlContent = buildMtl(scene);

  await mkdir(outDir, { recursive: true });
  await writeFile(path.join(outDir, 'model.obj'), objContent, 'utf8');
  await writeFile(path.join(outDir, 'model.mtl'), mtlContent, 'utf8');

  console.log(`Wrote ${path.join(outDir, 'model.obj')}`);
  console.log(`Wrote ${path.join(outDir, 'model.mtl')}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
